[package]
name = "pkmc-nbt"
version.workspace = true
edition.workspace = true

[dependencies]
pkmc-util = { path = "../pkmc-util" }
thiserror.workspace = true
serde = { version = "1.0.213", features = ["derive"] }
