[package]
name = "pkmc-nbt"
version.workspace = true
edition.workspace = true

[dependencies]
pkmc-util = { path = "../pkmc-util" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
