# address = "127.0.0.1:52817"
address = "[::1]:52817"
brand = "Vulae/pkmc"

# Number of bytes for a packet to get compressed
compression-threshold = 64
# Packet compression level 0..=9 (0 is no compression)
compression-level = 0
# NOTE: Compression is very buggy, See pkmc_util::connection::ZLibHandler

# world = "/home/vulae/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Fabulously Optimized 1.21.4/.minecraft/saves/pkmc/"
# NOTE: If you are loading an old world (<=1.19), you will want to optimize it first, or it will not load.
# Worlds > Edit World > Optimize World > Confirm (And wait (-.-)...Zzz)
# If it is a massive world you're optimizing, it's very likely you'll want to create a tmpfs directory for that folder.
# As Minecraft is extremely slow at doing this, and probably will be IO-limited (For some stupid reason, IDK)
world = "/home/vulae/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Fabulously Optimized 1.21.4/.minecraft/saves/Greenfield v0.5.4/"

view-distance = 32

[server-list]
text = "https://github.com/Vulae/pkmc"
# FIXME: Currently only supports .png format on release build.
# Please figure out how to build with all formats on release build.
icon = "server_icon.png"
# Icon filtering method to downscale/upscale image to 64x64 pixels.
# Possible values: Nearest, Triangle, CatmullRom, Gaussian, Lanczos3 (Default)
icon-filtering-method = "Nearest"

