# address = "127.0.0.1:52817"
address = "[::1]:52817"
brand = "Vulae/pkmc"

# Number of bytes for a packet to get compressed
compression-threshold = 64
# Packet compression level 0..=9 (0 is no compression)
compression-level = 3

world = "/home/vulae/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/pkmc/minecraft/saves/pkmc/"

[server-list]
text = "https://github.com/Vulae/pkmc"
# Icon MUST be a 64x64 png
icon = "server_icon.png"
