# address = "127.0.0.1:52817"
address = "[::1]:52817"
brand = "Vulae/pkmc"

# Number of bytes for a packet to get compressed
compression-threshold = 64
# Packet compression level 0..=9 (0 is no compression)
compression-level = 3

world = "/home/vulae/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/pkmc/minecraft/saves/pkmc/"

[server-list]
text = "https://github.com/Vulae/pkmc"
icon = "server_icon.png"
# Icon filtering method to downscale/upscale image to 64x64 pixels.
# Possible values: Nearest, Triangle, CatmullRom, Gaussian, Lanczos3 (Default)
icon-filtering-method = "Nearest"

