[package]
name = "pkmc-generated"
version.workspace = true
edition.workspace = true

[dependencies]
pkmc-generated-proc = { path = "../proc" }
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true