# address = "127.0.0.1:52817"
address = "[::1]:52817"
brand = "Vulae/pkmc"

online = true

# Number of bytes for a packet to get compressed
compression-threshold = 64
# Packet compression level 0..=9 (0 is no compression)
compression-level = 3

# NOTE: If you are loading an old world (<=1.19), you will want to optimize it first, or it will not load.
# Worlds > Edit World > Optimize World > Confirm (And wait (-.-)...Zzz)
# If it is a massive world you're optimizing, it's very likely you'll want to create a tmpfs directory for that folder.
# As Minecraft is extremely slow at doing this, and probably will be IO-limited (For some stupid reason, IDK)
# world = "/home/vulae/.local/share/PrismLauncher/instances/Fabulously Optimized 1.21.5/.minecraft/saves/pkmc/"
# world = "/home/vulae/.local/share/PrismLauncher/instances/Fabulously Optimized 1.21.4/.minecraft/saves/Greenfield v0.5.4/"
world = "/home/vulae/.local/share/PrismLauncher/instance_shared/vanilla/worlds/Survival/"

view-distance = 32
entity-distance = 256.0

# Supports formatting codes, with '&' as a replacement for '§'
# https://minecraft.wiki/w/Formatting_codes
motd-text = "&r&l&5Hello, World!&r   &8&o~Nya.&r                      &c█&6█&e█&a█&9█&5█\n&r&d&lhttps://github.com/Vulae/pkmc &r&c█&6█&e█&a█&9█&5█"
# Only supports .png by default, use the feature `full-image` to include more image formats. (`cargo run --release --features=full-image`)
motd-icon = "server_icon.png"
# Icon filtering method to downscale/upscale image to 64x64 pixels.
# Possible values: Nearest, Triangle, CatmullRom, Gaussian, Lanczos3 (Default)
motd-icon-filtering-method = "Lanczos3"
