[package]
name = "pkmc-packet"
version.workspace = true
edition.workspace = true

[dependencies]
pkmc-util = { path = "../pkmc-util" }
pkmc-nbt = { path = "../pkmc-nbt" }
thiserror.workspace = true
flate2 = "1.0.35"
